### ISSUE TITLE
avoid too generic identifiers to avoid possible clash with big apps

### ISSUE THREAD

**Issue by Alexey-T** [avk959/LGenerics#10]
```
const
  DEFAULT_DEPTH    = TJsonReader.DEF_DEPTH;
  DEFAULT_BUF_SIZE = TJsonReader.DEF_BUF_SIZE;
```

**Comment by Alexey-T** [comment]
e.g. add some prefix to them.

**Comment by avk959** [comment]
Could you please clarify what you are talking about?

**Comment by Alexey-T** [comment]
big app (many units) may have var with name DEFAULT_BUF_SIZE.

**Comment by avk959** [comment]
These constants were already part of the TJtdEntity class before I saw your message.

**Comment by Alexey-T** [comment]
better to rename these 2 consts. but you are the boss.
