### ISSUE TITLE
Can't compile lgenerics with fpc 3.2 and lazarus 2.0.1

### ISSUE THREAD

**Issue by MaLu28** [avk959/LGenerics#11]
Hi,

i want to use your package lgenerics at first time. But i have a problem to compile the package.
Can you tell me what can i do, whats wrong?

Thanks for your efforts.

**On compile lgenerics.lpk, the following error message appears:**

Hint: (11030) Start of reading config file C:\lazarus\fpc\3.2.0\bin\i386-win32\fpc.cfg
Hint: (11031) End of reading config file C:\lazarus\fpc\3.2.0\bin\i386-win32\fpc.cfg
Free Pascal Compiler version 3.2.0 [2020/07/07] for i386
Copyright (c) 1993-2020 by Florian Klaempfl and others
(1002) Target OS: Win32 for i386
(3104) Compiling lgenerics.pas
(3104) Compiling lgabstractcontainer.pas
(3104) Compiling lgutils.pas
(3104) Compiling lgstrconst.pas
(1010) Writing Resource String Table file: lgstrconst.rsj
(3104) Compiling lghelpers.pas
(3104) Compiling lghash.pas
..\LGenerics-master\lgenerics\lghelpers.pas(670,36) Hint: (4055) Conversion between ordinals and pointers is not portable
(3104) Compiling lgarrayhelpers.pas
..\LGenerics-master\lgenerics\lgarrayhelpers.pas(14980,23) Hint: (5058) Variable "aOfs" does not seem to be initialized
..\LGenerics-master\lgenerics\lgarrayhelpers.pas(33,8) Hint: (5023) Unit "lgHelpers" not used in lgArrayHelpers
(3104) Compiling lgasync.pas
(3104) Compiling lgqueue.pas
(3104) Compiling lgvector.pas
..\LGenerics-master\lgenerics\lgvector.pas(2541,41) Note: (6058) Call to subroutine "function BsfQWord(const AValue:QWord):DWord;" marked as inline is not inlined
(3104) Compiling lgpriorityqueue.pas
(3104) Compiling lgfunction.pas
(3104) Compiling lghashtable.pas
..\LGenerics-master\lgenerics\lghashtable.pas(34,8) Hint: (5023) Unit "lgHelpers" not used in lgHashTable
..\LGenerics-master\lgenerics\lgfunction.pas(181,3) Error: (1026) Compilation raised exception internally
Fatal: (1018) Compilation aborted
An unhandled exception occurred at $00470C1E:
EAccessViolation: Access violation
  $00470C1E
  $004AFED0
  $004AED50
  $004C61F0
  $004C6B88
  $004366BC
  $004B7076
  $00569C44
  $0056AACE
  $004366BC
  $004B7076
  $00569C44
  $0056AACE
  $004366BC
  $00414D05

Error: C:\lazarus\fpc\3.2.0\bin\i386-win32\ppc386.exe returned an error exitcode

**Comment by MaLu28** [comment]
Thanks for your fast answer.
I am trieed it in my sandbox. So it is not a problem to update these.
Today i go to vacation for on week. I try it after this and write you the result.

**Comment by MaLu28** [comment]
Hi,
i updated my FPC-Version from 3.2.0 to 3.2.2. Now i can compile the lgenerics-package.
Thanks for your help.

**Comment by avk959** [comment]
You're welcome.
