### ISSUE TITLE
No size specified and unable to determine the size of the operands

### ISSUE THREAD

**Issue by piula** [avk959/LGenerics#13]
Hello,

I recently upgraded FPC to most recent trunk snapshot and am now facing the following errors in compiling lgint128:

``lgint128.pas(1110,16) Error: No size specified and unable to determine the size of the operands``
``lgint128.pas(1673,15) Error: No size specified and unable to determine the size of the operands``
``lgint128.pas(1682,15) Error: No size specified and unable to determine the size of the operands``
``lgint128.pas(1684,15) Error: No size specified and unable to determine the size of the operands``
``lgint128.pas(1734,15) Error: No size specified and unable to determine the size of the operands``

I don't have much experience in ASM, so I appreciate any help to fix this error.

I am trying to cross-compile from win64 to win32.

Thank you :)

**Comment by avk959** [comment]
> I am trying to cross-compile from win64 to win32.

Is that really possible?

But it can be tried to be fixed, of course(done).

**Comment by piula** [comment]
Thank you 👍
