### ISSUE TITLE
Compiling package on macOS fails

### ISSUE THREAD

**Issue by frogfather** [avk959/LGenerics#14]
Error is 
lgasync.pas(2103,13) Error: Incompatible types: got "ShortInt" expected "TThreadID"
fpc 3.2.2 Lazarus 2.2.6
MacOS Ventura 13.6.1

Fixed locally by changing 
lgAsync line 2103  from  Result :=0; to Result := TThreadId(0);  
and
lgAsync line 2110 from Result := 0; to Result := TThreadId(0);

**Comment by avk959** [comment]
Thanks, never tested the library on the Mac. 
Fixed it, although it looks more like a compiler quirk.
