### ISSUE TITLE
LgHashMap Initialization issue:  cannot be determined whether it is due to the compiler or LGenrics.

### ISSUE THREAD

**Issue by uvwx413** [avk959/LGenerics#15]
Hello avk959!
   Thank you very much for excellent LGenerics library!
   
   I encountered an issue when applying HashMap. but I cannot determine whether it is due to the compiler or LGenrics.
   
```
type
  TTestMapSpec=specialize TGLiteHashMapLP<string, string, string>;
  TTestMap=TTestMapSpec TMap;

  TFoo=class
  private
    FMap: TTestMap;
    procedure DoInitialize; // Here, some Key-Val will be inserted into FMap
    procedure DoFinalize;
  public
    constructor Create;  // Calling DoInitialize
    destroyer Destroy; override;
   end;
```
  
----TFoo is working properly. But if a TBar is derived from TFoo, such as:
```
  TBar=class (TFoo)
  public
    constructor Create; // Call TFoo.Create
    destroyer Destroy; override;
  end;
```
  
----Execute TBar.Create will result in a memory overflow.
  Tracking the code reveals that it is constantly calling TGLiteHashTableLP.Resize(aNewCapacity: SizeInt);
  The difference is: 
      The "**class operator TGLiteHashTableLP.Initialize(var ht: TGLiteHashTableLP)**" is called before the body of the TFoo.Create
  while call TFoo.Create DIRECTLY, and it will be NOT while “TBar.Create ->TFoo.Create".
  
************so, it seems to be related to initialization, so
if defined
 `   TTestMap=specialize TGHashMapLP<string, string>;`
Modify
 ```
   TFoo.DoInitialize;
    begin
      FMap := TTestMap.Create;  // add this line, do Initialization
      ...
    end;
```
---  both  TFoo.Create and TBar.Create are working properly.

**Test Enviroment:  Win7-x64, Lazarus 3.2/FPC 3.2.2; LGenerics 0.56 or master version**

the test code attached here, note that the conditional compilation
[fb.zip](https://github.com/avk959/LGenerics/files/15111574/fb.zip)
```
 {$DEFINE LITE_VERSION}      // undefine this, both TFoo and TBar are working properly.
                                              // define LITE_VERSION, TFoo working properly, TBar go wrong.  
```
![2024-04-25 22 13 27](https://github.com/avk959/LGenerics/assets/72081475/242db232-eb4e-480f-b6ff-b524e4ef2d81)
![2024-04-25 22 12 31](https://github.com/avk959/LGenerics/assets/72081475/fa84c053-dea7-467e-b366-f55164cf0a8f)
![2024-04-25 22 13 07](https://github.com/avk959/LGenerics/assets/72081475/fb4991d7-f7ab-4027-b78c-b06371ef2fb4)

**Comment by avk959** [comment]
In this form, everything seems to work as expected.


[foo_bar.zip](https://github.com/avk959/LGenerics/files/15119232/foo_bar.zip)

> but I cannot determine whether it is due to the compiler or LGenrics.

So what will be the final verdict?

**Comment by uvwx413** [comment]
Yes, it works well!  and your  "print()" is simple and elgent. Thanks!

so, Explicitly initialize with “Initialize(FMap)” at bass class construtor is nesscessary.

The Wiki page about [management operators](https://wiki.freepascal.org/management_operators) say:

> The initialize operator is called directly after stack (or heap) memory allocation for a record happens.

it seems to be:  
   FMap's operator Initialize method is called implicitly while using ancestor TFoo  object
   and NOT called while using derived TBar object

**Comment by avk959** [comment]
>FMap's operator Initialize method is called implicitly while using ancestor TFoo object
> and NOT called while using derived TBar object

I believe this is a compiler bug.
