### ISSUE TITLE
The "Equitable" in `TGLiteEquitableHashMap` should be "Equatable"

### ISSUE THREAD

**Issue by Akira13641** [avk959/LGenerics#4]
They're both real words, but they have very different meanings:

Equ**i**table means "fair and impartial". 

Equ**a**table is the one relevant to hashmaps, and means "capable of being compared".

**Comment by avk959** [comment]
That's a good point, thank you. It seems fixed?

**Comment by Akira13641** [comment]
Yep, looks correct now!
