### ISSUE TITLE
FindMaxClique fail

### ISSUE THREAD

**Issue by armenha** [avk959/LGenerics#9]
TintChart.FindMaxClique failes with message Acces Violation in file lgsimplegraph.pas line 1642

function TGSimpleGraph.FindChordalMaxClique(out aClique: TIntSet): Boolean;
  procedure NodeDone(aIndex: SizeInt; const aLefts: TIntSet);
  begin
     _**if aLefts.Count > Pred(aClique.Count) then**_
      begin
        aClique.Assign(aLefts);
        aClique.Push(aIndex);
      end;
  end;
var
  Dummy: TIntArray;
begin
  aClique.Clear;
  Result := FindPerfectElimOrd(@NodeDone, Dummy);
  if not Result then
    aClique.Clear;
end;

**Comment by avk959** [comment]
Thanks for the reporting. Could you provide a small example that demonstrates this?

**Comment by armenha** [comment]
Sorry! I build another program for test wich work correctly. I found my mistake.
